import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
// import Card from '../ui/components/Card';
import styles from '../styles/Home.module.css';
// import UserCard from '../ui/home/UserCard';
import Navbar from '../ui/components/Navbar';
import Footer from '../ui/components/Footer';
import BannerCards from '../ui/components/BannerCard';
import FeaturedPost from '../ui/components/FeaturedPost';
import Features from '../ui/components/Features';
import Action from '../ui/components/Action';
import Testimonials from '../ui/components/Testimonials';
import Products from '../ui/components/Products';
import { useDispatch, useSelector } from '../store/store';
import { setHideLoadMore, setLoading, setPage, setProducts } from '../store/slices/productsSlice';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { products, page, limit } = useSelector((state) => state.products);

  const fetchProducts = async () => {
    try {
      dispatch(setLoading(true));
      const response = await fetch(`https://dummyjson.com/products?page=${page}&limit=${limit}`);
      const data = await response.json();
      const products = data.products || [];
      if (data.total === products.length) dispatch(setHideLoadMore(true));
      dispatch(setProducts(products));
      dispatch(setPage(page + 1));
    } catch (error) {
      console.error('Error fetching products:', error);
    } finally {
      dispatch(setLoading(false));
    }
  };

  useEffect(() => {
    fetchProducts();
  }, []); // Fetch products on component mount

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <BannerCards />
        <Products isIndex={true} fetchProducts={fetchProducts} />
        <Features />
        <FeaturedPost />
        <Testimonials />
        <Action />
        {/* <UserCard /> */}

        {/* <div className={styles.grid}>
          <Card
            title={'Box 1'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 2'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 3'}
            text={'Find in-depth information about Next.js features and API.'}
          />
          <Card
            title={'Box 4'}
            text={'Find in-depth information about Next.js features and API.'}
          />
        </div> */}
      </main>

      <Footer />

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
