import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../ui/components/Navbar';
import Footer from '../ui/components/Footer';
import BannerCards from '../ui/components/BannerCard';
import FeaturedPost from '../ui/components/FeaturedPost';
import Features from '../ui/components/Features';
import Action from '../ui/components/Action';
import Testimonials from '../ui/components/Testimonials';
import Products from '../ui/components/Products';
import { useDispatch, useSelector } from '../store/store';
import { setHideLoadMore, setLoading, setPage, setProducts } from '../store/slices/productsSlice';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { page, limit } = useSelector((state) => state.products);

  const fetchProducts = async () => {
    try {
      dispatch(setLoading(true));
      const response = await fetch(`https://dummyjson.com/products?page=${page}&limit=${limit}`);
      const data = await response.json();
      const products = data.products || [];
      if (data.total === products.length) dispatch(setHideLoadMore(true));
      dispatch(setProducts(products));
      dispatch(setPage(page + 1));
    } catch (error) {
      console.error('Error fetching products:', error);
    } finally {
      dispatch(setLoading(false));
    }
  };

  useEffect(() => {
    dispatch(setHideLoadMore(false));
    fetchProducts();
  }, []); // Fetch products on component mount

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <BannerCards />
        <Products isIndex={true} fetchProducts={fetchProducts} />
        <Features />
        <FeaturedPost />
        <Testimonials />
        <Action />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
